### ISSUE TITLE
EM looks broken

### ISSUE THREAD

**Issue by DanteArucard** [mattjj/pyhsmm-slds#16]
Dear Matthew,

I tried to modify the simple_demo.py to use EM_fit instead of the gibbs sampler but I obtain this error:
```
Traceback (most recent call last):
  File "simple_demo2.py", line 256, in <module>
    learnAndTestEM(inputs)
  File "simple_demo2.py", line 216, in learnAndTestEM
    test_model.EM_fit()#fit()
  File "/usr/local/lib/python2.7/site-packages/pybasicbayes/abstractions.py", line 221, in EM_fit
    return self._EM_fit(self.EM_step,tol=tol,maxiter=maxiter)
  File "/usr/local/lib/python2.7/site-packages/pybasicbayes/abstractions.py", line 206, in _EM_fit
    method()
  File "/usr/local/lib/python2.7/site-packages/pyhsmm/models.py", line 640, in EM_step
    self._M_step()
  File "/usr/local/lib/python2.7/site-packages/pyhsmm/models.py", line 647, in _M_step
    self._M_step_obs_distns()
  File "/usr/local/lib/python2.7/site-packages/pyhsmm/models.py", line 654, in _M_step_obs_distns
    [s.expected_states[:,state] for s in self.states_list])
  File "/usr/local/lib/python2.7/site-packages/pybasicbayes/distributions/regression.py", line 280, in max_likelihood
    else self._get_weighted_statistics(data,weights)
  File "/usr/local/lib/python2.7/site-packages/pybasicbayes/distributions/regression.py", line 154, in _get_weighted_statistics
    return sum((self._get_statistics(d) for d in data), self._empty_statistics())
ValueError: operands could not be broadcast together with shapes (2,2) (1,0) 
```

Compared to the demo in pyhsmm [`hmm-EM.py`](https://github.com/mattjj/pyhsmm/blob/master/examples/hmm-EM.py) the difference is obviously here:
`pyhsmm/models.py, line 654, in _M_step_obs_distns
    [s.expected_states[:,state] for s in self.states_list])` that calls  `max_likelihood(self,data,weights=None)`  in `pybasicbayes/distributions/gaussian.py line 432`

**Comment by slinderman** [comment]
Hi Dante,

I've recently added VBEM support to `pyslds`. Take a look at the `examples/vbem.py` demo and feel free to give it a shot.  

It's based on the variational approximation `q(x,z) = q(x) q(z)`, where `x` are the continuous latent states and `z` are the discrete latent states.  Both are given structured variational factors. 

--Scott
