### ISSUE TITLE
demo.py and AssertionError np.all(0 < np.linalg.eigvalsh(S))

### ISSUE THREAD

**Issue by clemense** [mattjj/pyhsmm-slds#2]
Hi,
When running python examples/demo.py I get the following error:

Traceback (most recent call last):
  File "examples/demo.py", line 107, in <module>
    model.resample_model()
  File "/usr/local/lib/python2.7/dist-packages/pyhsmm/models.py", line 430, in resample_model
    self.resample_parameters()
  File "/home/someuser/code/pyhsmm-slds/pyslds/models.py", line 36, in resample_parameters
    self.resample_lds_parameters()
  File "/home/someuser/code/pyhsmm-slds/pyslds/models.py", line 41, in resample_lds_parameters
    self.resample_dynamics_distns()
  File "/home/someuser/code/pyhsmm-slds/pyslds/models.py", line 58, in resample_dynamics_distns
    for s in self.states_list])
  File "/home/someuser/.local/lib/python2.7/site-packages/pybasicbayes/distributions/regression.py", line 257, in resample
    *self._natural_to_standard(self.natural_hypparam + stats))
  File "/home/someuser/.local/lib/python2.7/site-packages/pybasicbayes/distributions/regression.py", line 97, in _natural_to_standard
    assert np.all(0 < np.linalg.eigvalsh(S))
AssertionError

My numpy version is 1.8.2.
What could be the problem?

Thanks!

**Comment by mattjj** [comment]
Can you try upgrading numpy? I'm on 1.11.0 on this laptop and I don't see that error. Also try moving to the most recent version of pylds (clone the github master branch and do a `pip install -e .`).

**Comment by clemense** [comment]
Thanks, solved it!
