### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by kunalmenda** [mattjj/pyhsmm-slds#32]
Hi, thanks for this awesome package! I'm having some installation issues, and have shown the console output below. 

I'm running MacOS Catalina, and attempting to `pip` install in a `conda` environment. 

Please let me know if you have any suggestions, or would like additional information. Thanks!

```
pip install pyslds
Collecting pyslds
  Downloading pyslds-0.0.3.tar.gz (11 kB)
Requirement already satisfied: numpy in /Users/kunalmenda/anaconda3/lib/python3.6/site-packages (from pyslds) (1.16.1)
Requirement already satisfied: scipy in /Users/kunalmenda/anaconda3/lib/python3.6/site-packages (from pyslds) (1.3.1)
Requirement already satisfied: matplotlib in /Users/kunalmenda/anaconda3/lib/python3.6/site-packages (from pyslds) (3.0.2)
Collecting pybasicbayes
  Downloading pybasicbayes-0.2.2.tar.gz (212 kB)
     |████████████████████████████████| 212 kB 2.9 MB/s 
Collecting pyhsmm
  Downloading pyhsmm-0.1.7.tar.gz (513 kB)
     |████████████████████████████████| 513 kB 2.7 MB/s 
    ERROR: Command errored out with exit status 1:
     command: /Users/kunalmenda/anaconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/bd/3_hzrx6n6r75tb67qfy2g5n80000gn/T/pip-install-h8gmheg7/pyhsmm/setup.py'"'"'; __file__='"'"'/private/var/folders/bd/3_hzrx6n6r75tb67qfy2g5n80000gn/T/pip-install-h8gmheg7/pyhsmm/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/bd/3_hzrx6n6r75tb67qfy2g5n80000gn/T/pip-pip-egg-info-qye15z90
         cwd: /private/var/folders/bd/3_hzrx6n6r75tb67qfy2g5n80000gn/T/pip-install-h8gmheg7/pyhsmm/
    Complete output (30 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/bd/3_hzrx6n6r75tb67qfy2g5n80000gn/T/pip-install-h8gmheg7/pyhsmm/setup.py", line 76, in <module>
        urlretrieve(eigenurl, eigentarpath)
      File "/Users/kunalmenda/anaconda3/lib/python3.6/urllib/request.py", line 248, in urlretrieve
        with contextlib.closing(urlopen(url, data)) as fp:
      File "/Users/kunalmenda/anaconda3/lib/python3.6/urllib/request.py", line 223, in urlopen
        return opener.open(url, data, timeout)
      File "/Users/kunalmenda/anaconda3/lib/python3.6/urllib/request.py", line 532, in open
        response = meth(req, response)
      File "/Users/kunalmenda/anaconda3/lib/python3.6/urllib/request.py", line 642, in http_response
        'http', request, response, code, msg, hdrs)
      File "/Users/kunalmenda/anaconda3/lib/python3.6/urllib/request.py", line 564, in error
        result = self._call_chain(*args)
      File "/Users/kunalmenda/anaconda3/lib/python3.6/urllib/request.py", line 504, in _call_chain
        result = func(*args)
      File "/Users/kunalmenda/anaconda3/lib/python3.6/urllib/request.py", line 756, in http_error_302
        return self.parent.open(new, timeout=req.timeout)
      File "/Users/kunalmenda/anaconda3/lib/python3.6/urllib/request.py", line 532, in open
        response = meth(req, response)
      File "/Users/kunalmenda/anaconda3/lib/python3.6/urllib/request.py", line 642, in http_response
        'http', request, response, code, msg, hdrs)
      File "/Users/kunalmenda/anaconda3/lib/python3.6/urllib/request.py", line 570, in error
        return self._call_chain(*args)
      File "/Users/kunalmenda/anaconda3/lib/python3.6/urllib/request.py", line 504, in _call_chain
        result = func(*args)
      File "/Users/kunalmenda/anaconda3/lib/python3.6/urllib/request.py", line 650, in http_error_default
        raise HTTPError(req.full_url, code, msg, hdrs, fp)
    urllib.error.HTTPError: HTTP Error 404: Not Found
    Downloading Eigen...
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.```

**Comment by slinderman** [comment]
Hi Kunal, please try cloning the latest from github and installing from
source (`cd pylds; pip install -e .`).

**Comment by kunalmenda** [comment]
Thanks for the swift response!

I'm getting the same error when I try this:

```
git clone https://github.com/mattjj/pyslds.git
cd pyslds/
pip install -e .
Obtaining file:///Users/kunalmenda/Desktop/pyslds
Requirement already satisfied: numpy in /Users/kunalmenda/anaconda3/lib/python3.6/site-packages (from pyslds==0.0.3) (1.16.1)
Requirement already satisfied: scipy in /Users/kunalmenda/anaconda3/lib/python3.6/site-packages (from pyslds==0.0.3) (1.3.1)
Requirement already satisfied: matplotlib in /Users/kunalmenda/anaconda3/lib/python3.6/site-packages (from pyslds==0.0.3) (3.0.2)
Collecting pybasicbayes
  Using cached pybasicbayes-0.2.2.tar.gz (212 kB)
Collecting pyhsmm
  Using cached pyhsmm-0.1.7.tar.gz (513 kB)
    ERROR: Command errored out with exit status 1:
     command: /Users/kunalmenda/anaconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/bd/3_hzrx6n6r75tb67qfy2g5n80000gn/T/pip-install-hlys7x_n/pyhsmm/setup.py'"'"'; __file__='"'"'/private/var/folders/bd/3_hzrx6n6r75tb67qfy2g5n80000gn/T/pip-install-hlys7x_n/pyhsmm/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/bd/3_hzrx6n6r75tb67qfy2g5n80000gn/T/pip-pip-egg-info-_ibd7kv_
         cwd: /private/var/folders/bd/3_hzrx6n6r75tb67qfy2g5n80000gn/T/pip-install-hlys7x_n/pyhsmm/
    Complete output (30 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/bd/3_hzrx6n6r75tb67qfy2g5n80000gn/T/pip-install-hlys7x_n/pyhsmm/setup.py", line 76, in <module>
        urlretrieve(eigenurl, eigentarpath)
      File "/Users/kunalmenda/anaconda3/lib/python3.6/urllib/request.py", line 248, in urlretrieve
        with contextlib.closing(urlopen(url, data)) as fp:
      File "/Users/kunalmenda/anaconda3/lib/python3.6/urllib/request.py", line 223, in urlopen
        return opener.open(url, data, timeout)
      File "/Users/kunalmenda/anaconda3/lib/python3.6/urllib/request.py", line 532, in open
        response = meth(req, response)
      File "/Users/kunalmenda/anaconda3/lib/python3.6/urllib/request.py", line 642, in http_response
        'http', request, response, code, msg, hdrs)
      File "/Users/kunalmenda/anaconda3/lib/python3.6/urllib/request.py", line 564, in error
        result = self._call_chain(*args)
      File "/Users/kunalmenda/anaconda3/lib/python3.6/urllib/request.py", line 504, in _call_chain
        result = func(*args)
      File "/Users/kunalmenda/anaconda3/lib/python3.6/urllib/request.py", line 756, in http_error_302
        return self.parent.open(new, timeout=req.timeout)
      File "/Users/kunalmenda/anaconda3/lib/python3.6/urllib/request.py", line 532, in open
        response = meth(req, response)
      File "/Users/kunalmenda/anaconda3/lib/python3.6/urllib/request.py", line 642, in http_response
        'http', request, response, code, msg, hdrs)
      File "/Users/kunalmenda/anaconda3/lib/python3.6/urllib/request.py", line 570, in error
        return self._call_chain(*args)
      File "/Users/kunalmenda/anaconda3/lib/python3.6/urllib/request.py", line 504, in _call_chain
        result = func(*args)
      File "/Users/kunalmenda/anaconda3/lib/python3.6/urllib/request.py", line 650, in http_error_default
        raise HTTPError(req.full_url, code, msg, hdrs, fp)
    urllib.error.HTTPError: HTTP Error 404: Not Found
    Downloading Eigen...
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by slinderman** [comment]
I’d do the same with dependencies PyBasicbayes, PyHSMM, Pylds, etc. you can see it’s breaking during the PyHSMM install.

Best,
Scott
